<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit employee recommendation');

if(isset($_GET['employee_recommendation_id']))
{
    $employee_recommendation_id = urldecode($_GET['employee_recommendation_id']);
    require 'form_data_employee_recommendation.php';

}

$anchor_tag = '';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/employee_recommendation.php';
    $dbh_employee_recommendation = new employee_recommendation;

    $object_name = 'dbh_employee_recommendation';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_employee_recommendation.php?$query_string");
    }

    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_employee_recommendation->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_employee_recommendation->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {

            $dbh_employee_recommendation->edit($arr_form_data);

            redirect("listview_employee_recommendation.php?$query_string");
        }
    }
}
require 'subclasses/employee_recommendation_html.php';
$html = new employee_recommendation_html;
$html->draw_header('Edit %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('employee_recommendation_id');

$html->draw_controls('edit');

$html->draw_footer();