<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete question header');

if(isset($_GET['question_header_id']))
{
    $question_header_id = urldecode($_GET['question_header_id']);
    require_once 'form_data_question_header.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_question_header.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/question_header.php';
        $dbh_question_header = new question_header;

        $object_name = 'dbh_question_header';
        require 'components/create_form_data.php';

        require_once 'subclasses/question_details.php';
        $dbh_question_details = new question_details;
        $dbh_question_details->delete_many($arr_form_data);


        $dbh_question_header->delete($arr_form_data);

        redirect("listview_question_header.php?$query_string");
    }
}
require 'subclasses/question_header_html.php';
$html = new question_header_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('question_header_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();